In [2]:
from pathlib import Path
import pandas as pd
housing_full = pd.read_csv(Path("datasets/housing/housing.csv"))

In [3]:
housing_full.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [8]:
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib as lb
housing_full["income_cat"] = pd.cut(housing_full["median_income"],bins=[0.,1.5,3.,4.5,6.,np.inf],labels=[1,2,3,4,5])
stat_train_set,stat_test_set = train_test_split(
housing_full, test_size=0.2, stratify=housing_full["income_cat"],
random_state=42)
housing_1 = stat_train_set.copy()
housing_1.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,income_cat
13096,-122.42,37.80,52.0,3321.0,1115.0,1576.0,1034.0,2.0987,458300.0,NEAR BAY,2
14973,-118.38,34.14,40.0,1965.0,354.0,666.0,357.0,6.0876,483800.0,<1H OCEAN,5
3785,-121.98,38.36,33.0,1083.0,217.0,562.0,203.0,2.4330,101700.0,INLAND,2
14689,-117.11,33.75,17.0,4174.0,851.0,1845.0,780.0,2.2618,96100.0,INLAND,2
20507,-118.15,33.77,36.0,4366.0,1211.0,1912.0,1172.0,3.5292,361800.0,NEAR OCEAN,3

In [9]:
corr_matrix = housing_1.corr(numeric_only = True)
print(corr_matrix)

                    longitude  latitude  housing_median_age  total_rooms  \
longitude            1.000000 -0.924213           -0.102937     0.044558
latitude            -0.924213  1.000000            0.005692    -0.036753
housing_median_age  -0.102937  0.005692            1.000000    -0.361710
total_rooms          0.044558 -0.036753           -0.361710     1.000000
total_bedrooms       0.068210 -0.066391           -0.317978     0.930076
population           0.104236 -0.115677           -0.301906     0.863967
households           0.054261 -0.071604           -0.300075     0.916143
median_income       -0.016542 -0.078137           -0.127043     0.197720
median_house_value  -0.050859 -0.139584            0.102175     0.137455

                    total_bedrooms  population  households  median_income  \
longitude                 0.068210    0.104236    0.054261      -0.016542
latitude                 -0.066391   -0.115677   -0.071604      -0.078137
housing_median_age       -0.317978   -0.301906   -0.300075      -0.127043
total_rooms               0.930076    0.863967    0.916143       0.197720
total_bedrooms            1.000000    0.886200    0.978822      -0.006038
population                0.886200    1.000000    0.916237       0.004282
households                0.978822    0.916237    1.000000       0.013637
median_income            -0.006038    0.004282    0.013637       1.000000
median_house_value        0.054635   -0.020153    0.071426       0.688380

                    median_house_value
longitude                    -0.050859
latitude                     -0.139584
housing_median_age            0.102175
total_rooms                   0.137455
total_bedrooms                0.054635
population                   -0.020153
households                    0.071426
median_income                 0.688380
median_house_value            1.000000

In [11]:
housing_1["income_cat"].dtype

CategoricalDtype(categories=[1, 2, 3, 4, 5], ordered=True, categories_dtype=int64)

In [12]:
housing_1["rooms_per_house"] = housing_1["total_rooms"] / housing_1["households"]
housing_1["bedrooms_ratio"] = housing_1["total_bedrooms"] / housing_1["total_rooms"]
housing_1["people_per_house"] = housing_1["population"] / housing_1["households"]
corr_matrix = housing_1.corr(numeric_only = True)
corr_matrix["median_house_value"].sort_values(ascending = False)

median_house_value    1.000000
median_income         0.688380
rooms_per_house       0.143663
total_rooms           0.137455
housing_median_age    0.102175
households            0.071426
total_bedrooms        0.054635
population           -0.020153
people_per_house     -0.038224
longitude            -0.050859
latitude             -0.139584
bedrooms_ratio       -0.256397
Name: median_house_value, dtype: float64

In [16]:
housing = housing_1.drop("median_house_value",axis = 1)

In [20]:
housing_labels = housing_1["median_house_value"].copy()

In [19]:
# from sklearn.impute import SimpleImputer
# imputer = SimpleImputer(strategy = "median")
# housing_num = housing.select_dtypes(include = [np.number])
# imputer.fit(housing_num)

In [23]:
print(housing_labels.count())
print(housing["total_bedrooms"].count())

16512
16344

In [24]:
housing["bedrooms_ratio"].count()

np.int64(16344)

In [32]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
num_pipeline = make_pipeline(SimpleImputer(strategy = "median") ,StandardScaler())
from sklearn.compose import ColumnTransformer
num_attributes = ["longitude", "latitude", "housing_median_age", "rooms_per_house",
"bedrooms_ratio", "people_per_house", "households", "median_income"]
cat_attributes = ["ocean_proximity"]
cat_pipeline = make_pipeline(
SimpleImputer(strategy="most_frequent"),
OneHotEncoder(handle_unknown="ignore",drop = "first"))
preprocessing = ColumnTransformer([
("num", num_pipeline, num_attributes),
("cat", cat_pipeline, cat_attributes),
])

In [33]:
from sklearn.compose import make_column_selector, make_column_transformer
preprocessing = make_column_transformer(
(num_pipeline, make_column_selector(dtype_include=np.number)),
(cat_pipeline, make_column_selector(dtype_include=object)),
)
housing_prepared = preprocessing.fit_transform(housing)
housing_prepared.shape

(16512, 15)

In [36]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(housing_prepared,housing_labels)

housing_predictions = model.predict(housing_prepared)
housing_predictions[:5].round(-2)

array([281800., 333300., 117000., 104900., 309100.])

In [37]:
 housing_labels.iloc[:5].values

array([458300., 483800., 101700.,  96100., 361800.])

In [38]:
from sklearn.metrics import root_mean_squared_error
lin_rmse = root_mean_squared_error(housing_labels, housing_predictions)
lin_rmse

67269.98114035041

In [39]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = make_pipeline(preprocessing, DecisionTreeRegressor(random_state=42))
tree_reg.fit(housing, housing_labels)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000019A6D8782F0>),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x0000019A6D9B4A50>)])),
                ('decisiontreeregressor',
                 DecisionTreeRegressor(random_state=42))])

In [41]:
housing_predictions = tree_reg.predict(housing)
tree_rmse = root_mean_squared_error(housing_labels, housing_predictions)
tree_rmse

0.0

In [45]:
X_test = stat_test_set.drop("median_house_value", axis=1)
y_test = stat_test_set["median_house_value"].copy()
X_test["rooms_per_house"] = X_test["total_rooms"] / X_test["households"]
X_test["bedrooms_ratio"] = X_test["total_bedrooms"] / X_test["total_rooms"]
X_test["people_per_house"] = X_test["population"] / X_test["households"]
x_test = preprocessing.fit_transform(X_test)
final_predictions = model.predict(x_test)
final_rmse = root_mean_squared_error(y_test, final_predictions)
print(final_rmse)

70022.24872127303

In [46]:
from scipy import stats
def rmse(squared_errors):
    return np.sqrt(np.mean(squared_errors))
confidence = 0.95
squared_errors = (final_predictions - y_test) ** 2
boot_result = stats.bootstrap(
    [squared_errors], rmse,
confidence_level=confidence, random_state=42)
rmse_lower, rmse_upper = boot_result.confidence_interval

In [47]:
rmse_lower

np.float64(67349.65992182685)

In [48]:
rmse_upper

np.float64(74006.16658781466)